server:
  port: 9003
spring:
  application:
    name: PAYMENT-SERVICE
  zipkin:
    base-url: http://127.0.0.1:9411/
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/miniproject2
    username: spring
    password: spring
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
